kaa_node:
    image: kaaproject/node:0.9.0
    environment:
        - DATABASE=cassandra
        - ZK_HOSTS=zookeeperhost:2181
        - CASSANDRA_HOSTS=cassandrahost:9042
        - MONGODB_HOSTS=mongodbhost:27017
        - JDBC_HOST=postgreshost
        - JDBC_PORT=5432
    command: bash -c "/config_listener.sh && /usr/bin/kaa-node start && while true; do sleep 1; done"
