version: '2'
services:
  kaa_0:
    image: kaa-node:0.10.0
    env_file: kaa-example.env
    environment:
      - SQL_PROVIDER_NAME=mariadb # (postgresql, default: mariadb)
      - NOSQL_PROVIDER_NAME=mongodb # (cassandra, default: mongodb)
      - SERVICES_WAIT_TIMEOUT=-1 # Wait forever for Zookeeper and SQL
      - ADMIN_PORT=10080
      - BOOTSTRAP_TCP=10088
      - BOOTSTRAP_HTTP=10089
      - OPERATIONS_TCP=10097
      - OPERATIONS_HTTP=10099
    networks:
      - back-tier
      - front-tier
    ports:
      - "10080:10080"
      - "10088:10088"
      - "10089:10089"
      - "10097:10097"
      - "10099:10099"
text to insert
networks:
  back-tier:
    driver: bridge
  front-tier:
    driver: bridge
  kaa_1 :
    image: kaa-node:0.10.0
    env_file: kaa-example.env
    environment:
      - SQL_PROVIDER_NAME=mariadb # (postgresql, default: mariadb)
      - NOSQL_PROVIDER_NAME=mongodb # (cassandra, default: mongodb)
      - SERVICES_WAIT_TIMEOUT=-1 # Wait forever for Zookeeper and SQL
      - ADMIN_PORT=10180
      - BOOTSTRAP_TCP=10188
      - BOOTSTRAP_HTTP=10189
      - OPERATIONS_TCP=10197
      - OPERATIONS_HTTP=10199
    networks:
      - back-tier
      - front-tier
    ports:
      - "10180:10180"
      - "10188:10188"
      - "10189:10189"
      - "10197:10197"
