# Run Kaa IoT using MariaDB and MongoDB

version: '2'
services:
  sql:
    image: mariadb:5.5
    networks:
      - back-tier
    volumes:
      - sql-data:/var/lib/sql
    env_file: mariadb-sql-example.env
  zookeeper:
    image: jplock/zookeeper:3.4.8
    networks:
      - back-tier
    volumes:
      - zookeeper-data:/tmp/zookeeper
  nosql:
    image: mongo:3.2
    networks:
      - back-tier
    volumes:
      - nosql-data:/data/db
networks:
  back-tier:
    driver: bridge # overlay for Swarm (unreleased update)
  front-tier:
    driver: bridge # overlay for Swarm (unreleased update)
volumes:
  sql-data:
  nosql-data:
  zookeeper-data:
